=== berdayespablo/DTDs/DTD-6/6_1bDTD.dtd
<!ELEMENT songs (song+)>
<!ELEMENT song (title, composers, producers, publisher, artists)>
<!ELEMENT composers (composer)>
<!ELEMENT composer (nombre, apellidos)>
<!ELEMENT producers (producer)>
<!ELEMENT producer (nombre, apellidos)>
<!ELEMENT artists (artist)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT artist (#PCDATA)>
<!ATTLIST song length CDATA #REQUIRED>
<!ATTLIST song anio CDATA #REQUIRED>

=== berdayespablo/DTDs/DTD-6/6_1b.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE song SYSTEM "6_1bDTD.dtd">
<song length="6.20" anio="1978">
  <title>Hot Cop</title>
  <composers>
    <composer>
      <nombre>Henry</nombre>
      <apellidos>Beolo</apellidos>
    </composer>
  </composers>
  <producers>
    <producer>
      <nombre>Jacques</nombre>
      <apellidos>Morali</apellidos>
    </producer>  
  </producers>
  <publisher>PolyGram</publisher>
  <artists>
  <artist>Village People</artist>
  </artists>
</song>
