<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resultados [
<!ELEMENT resultados (partido*)>
  <!ELEMENT partido (equipo)*>
  <!ELEMENT equipo (#PCDATA)>
  <!ATTLIST equipo goles CDATA #REQUIRED>
]>
<resultados>
    <partido>
      <equipo goles="0">Nottingham Prisa</equipo>
      <equipo goles="1">Inter de Mitente</equipo>
    </partido>
    <partido>
      <equipo goles="3">Vodka Juniors</equipo>
      <equipo goles="3">Sparta da Risa</equipo>
    </partido>
    <partido>
      <equipo goles="4">Water de Munich</equipo>
      <equipo goles="2">Esteaua es del Grifo</equipo>
    </partido>
  </resultados>